# Generated by Django 2.1.5 on 2019-02-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('cama', models.CharField(max_length=5, verbose_name='Cama')),
                ('condicion', models.CharField(max_length=50, verbose_name='Condicion')),
                ('dolencia', models.CharField(max_length=200, verbose_name='Dolencia')),
                ('medico', models.CharField(max_length=200, verbose_name='Medico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
