# Generated by Django 2.1.5 on 2019-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(max_length=200, verbose_name='Paciente')),
                ('insumos', models.TextField(verbose_name='Insumos')),
                ('solicitante', models.CharField(max_length=200, verbose_name='Solicitante')),
                ('procesante', models.CharField(max_length=200, verbose_name='Procesante')),
                ('retirante', models.CharField(max_length=200, verbose_name='Retirante')),
                ('urgencia', models.CharField(max_length=100, verbose_name='Urgencia')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('id_modificado', models.CharField(max_length=50, verbose_name='modificado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('fecha_procesamiento', models.DateTimeField(verbose_name='Fecha de procesamiento')),
                ('fecha_despachable', models.DateTimeField(verbose_name='Fecha despachable')),
                ('fecha_despacho', models.DateTimeField(verbose_name='Fecha de despacho')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['urgencia', 'created'],
            },
        ),
    ]
