# Generated by Django 2.1.5 on 2019-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cama',
            field=models.CharField(default=None, max_length=100, verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
