# Generated by Django 2.1.5 on 2019-02-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20190218_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cama',
            field=models.CharField(default='0000000', max_length=100, verbose_name='Paciente'),
        ),
    ]
