# Generated by Django 2.1.5 on 2019-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20190218_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cama',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cama'),
        ),
    ]
