# Generated by Django 2.1.5 on 2019-02-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20190218_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['-urgencia', 'created'], 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_modificado',
            field=models.CharField(default='no', max_length=50, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='procesante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Procesante'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='retirante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Retirante'),
        ),
    ]
