# Generated by Django 2.1.5 on 2019-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20190219_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_despachable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha despachable'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de despacho'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
    ]
