# Generated by Django 2.1.5 on 2019-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20190324_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='created',
            field=models.CharField(blank=True, default='24/03/2019 10:42:27', max_length=100, verbose_name='Fecha de creación'),
        ),
    ]
